# Generated by Django 3.1 on 2020-08-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
